In [1]:
import numpy             as np
from new_jacobi import JacobiOperator

In [2]:
A = JacobiOperator('A')
B = JacobiOperator('B')
C = JacobiOperator('C')
D = JacobiOperator('D')

In [3]:
nab = (5,1/2,1/2)

def show(X,*args): 
    print(X(*args).todense())
    print()
    
show(D(+1),*nab)
show(D(-1),*nab)
show(D(+1) @ D(-1),*nab)

[[0.  1.5 0.  0.  0.  0. ]
 [0.  0.  2.  0.  0.  0. ]
 [0.  0.  0.  2.5 0.  0. ]
 [0.  0.  0.  0.  3.  0. ]
 [0.  0.  0.  0.  0.  3.5]]

[[ 0  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0 12]]

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.]
 [ 0.  0.  9.  0.  0.  0.]
 [ 0.  0.  0. 16.  0.  0.]
 [ 0.  0.  0.  0. 25.  0.]
 [ 0.  0.  0.  0.  0. 36.]]



In [4]:
nab = (50,4,3/2)

def norm(X,*args): 
    e = np.max(np.abs(X(*args)))
    print(e < 1e-12)

# X * Y = X @ Y - Y @ X
M = D(+1) * D(-1)
S = C(+1) * C(-1)

norm( M * S ,*nab)

for p in (-1,1):
    
    norm( M * D(p) - 2*p*D(p) ,*nab)
    norm( M * C(p)            ,*nab)
    norm( M * A(p) -   p*A(p) ,*nab)
    norm( M * B(p) -   p*B(p) ,*nab)
    
    norm( S * D(p)            ,*nab)
    norm( S * C(p) - 2*p*C(p) ,*nab)
    norm( S * A(p) -   p*A(p) ,*nab)
    norm( S * B(p) +   p*B(p) ,*nab)
    
    norm( D(p) * C(+p) ,*nab)
    norm( D(p) * C(-p) ,*nab)
    
    norm( A(p) * D(+p)           ,*nab)
    norm( A(p) * D(-p) + p*B(-p) ,*nab)
    norm( A(p) * C(+p)           ,*nab)
    norm( A(p) * C(-p) + p*B(+p) ,*nab)
    
    norm( B(p) * D(+p)           ,*nab)
    norm( B(p) * D(-p) - p*A(-p) ,*nab)
    norm( B(p) * C(+p) + p*A(+p) ,*nab)
    norm( B(p) * C(-p)           ,*nab)
    
    norm( A(p) * B(+p) ,*nab)
    norm( A(p) * B(-p) ,*nab)

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [5]:
nab = (5,1/2,1/2)

I = (B(-1) @ B(+1) + A(-1) @ A(+1))/2
J = (B(-1) @ B(+1) - A(-1) @ A(+1))/2

show(I,*nab)
show(J,*nab)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0.         0.375      0.         0.         0.         0.        ]
 [0.66666667 0.         0.41666667 0.         0.         0.        ]
 [0.         0.6        0.         0.4375     0.         0.        ]
 [0.         0.         0.57142857 0.         0.45       0.        ]
 [0.         0.         0.         0.55555556 0.         0.45833333]
 [0.         0.         0.         0.         0.54545455 0.        ]
 [0.         0.         0.         0.         0.         0.53846154]]

