In [1]:
import numpy             as np
from new_jacobi import JacobiOperator, LaguerreOperator, HermiteOperator

In [2]:
A = JacobiOperator('A')
B = JacobiOperator('B')
C = JacobiOperator('C')
D = JacobiOperator('D')

In [3]:
nab = (5,1/2,1/2)

def show(X,*args): 
    print(X(*args))
    print()
    
show(D(+1),*nab)
show(D(-1),*nab)
show(D(+1) @ D(-1),*nab)

[[0.  1.5 0.  0.  0.  0. ]
 [0.  0.  2.  0.  0.  0. ]
 [0.  0.  0.  2.5 0.  0. ]
 [0.  0.  0.  0.  3.  0. ]
 [0.  0.  0.  0.  0.  3.5]]

[[ 0  0  0  0  0  0]
 [ 2  0  0  0  0  0]
 [ 0  4  0  0  0  0]
 [ 0  0  6  0  0  0]
 [ 0  0  0  8  0  0]
 [ 0  0  0  0 10  0]
 [ 0  0  0  0  0 12]]

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  4.  0.  0.  0.  0.]
 [ 0.  0.  9.  0.  0.  0.]
 [ 0.  0.  0. 16.  0.  0.]
 [ 0.  0.  0.  0. 25.  0.]
 [ 0.  0.  0.  0.  0. 36.]]



In [4]:
nab = (5,4,3/2)

def norm(X,eps=1e-10): 
    print(np.max(np.abs(X(*nab))) < eps)

# X * Y = X @ Y - Y @ X
M = D(+1) * D(-1)
S = C(+1) * C(-1)

norm( M * S )

for p in (-1,1):
    
    norm( M * D(p) - 2*p*D(p) )
    norm( M * C(p)            )
    norm( M * A(p) -   p*A(p) )
    norm( M * B(p) -   p*B(p) )
    
    norm( S * D(p)            )
    norm( S * C(p) - 2*p*C(p) )
    norm( S * A(p) -   p*A(p) )
    norm( S * B(p) +   p*B(p) )
    
    norm( D(p) * C(+p) )
    norm( D(p) * C(-p) )
    
    norm( A(p) * D(+p)           )
    norm( A(p) * D(-p) + p*B(-p) )
    norm( A(p) * C(+p)           )
    norm( A(p) * C(-p) + p*B(+p) )
    
    norm( B(p) * D(+p)           )
    norm( B(p) * D(-p) - p*A(-p) )
    norm( B(p) * C(+p) + p*A(+p) )
    norm( B(p) * C(-p)           )
    
    norm( A(p) * B(+p) )
    norm( A(p) * B(-p) )

True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True
True


In [5]:
nab = (5,1/2,1/2)

I = (B(-1) @ B(+1) + A(-1) @ A(+1))/2
J = (B(-1) @ B(+1) - A(-1) @ A(+1))/2

show(I,*nab)
show(J,*nab)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0.         0.375      0.         0.         0.         0.        ]
 [0.66666667 0.         0.41666667 0.         0.         0.        ]
 [0.         0.6        0.         0.4375     0.         0.        ]
 [0.         0.         0.57142857 0.         0.45       0.        ]
 [0.         0.         0.         0.55555556 0.         0.45833333]
 [0.         0.         0.         0.         0.54545455 0.        ]
 [0.         0.         0.         0.         0.         0.53846154]]



In [6]:
A = LaguerreOperator("A")
D = LaguerreOperator("D")
C = lambda p: D(p) - p*A(p)

In [7]:
na = (5,3)

show(D(-1)*D(+1),*na)

show(D(-1)*A(+1),*na)
show(D(+1)*A(-1),*na)

show(C(-1)*C(+1),*na)

show(C(-1)*A(+1),*na)
show(C(+1)*A(-1),*na)

show(D(+1)*A(+1),*na)
show(D(-1)*A(-1),*na)

show(C(-1)*D(+1),*na)
show(C(-1)*D(-1),*na)
show(C(+1)*D(+1),*na)
show(C(+1)*D(-1),*na)
show(C(-1)*A(-1),*na)
show(C(+1)*A(+1),*na)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

[[-1.  0.  0.  0.  0.  0.]
 [ 0. -1.  0.  0.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.]
 [ 0.  0.  0. -1.  0.  0.]
 [ 0.  0.  0.  0. -1.  0.]
 [ 0.  0.  0.  0.  0. -1.]
 [ 0.  0.  0.  0.  0.  0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [48]:
A = HermiteOperator()

In [49]:
n = 5
I = A(+1)*A(-1)/2
print(I(n))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [62]:
X = (A(+1) + A(-1))/2
print(X(n))

[[0.  1.  0.  0.  0.  0. ]
 [0.5 0.  2.  0.  0.  0. ]
 [0.  0.5 0.  3.  0.  0. ]
 [0.  0.  0.5 0.  4.  0. ]
 [0.  0.  0.  0.5 0.  5. ]
 [0.  0.  0.  0.  0.5 0. ]
 [0.  0.  0.  0.  0.  0.5]]
